province={
	"result": 1,
	"data": {
		"provinces": [{
			"id": 1,
			"provinceName": "北京市",
			"provinceRemark": "直辖市",
			"provinceSort": 1
		}, {
			"id": 2,
			"provinceName": "天津市",
			"provinceRemark": "直辖市",
			"provinceSort": 2
		}, {
			"id": 3,
			"provinceName": "河北省",
			"provinceRemark": "省份",
			"provinceSort": 5
		}, {
			"id": 4,
			"provinceName": "山西省",
			"provinceRemark": "省份",
			"provinceSort": 6
		}, {
			"id": 5,
			"provinceName": "内蒙古自治区",
			"provinceRemark": "自治区",
			"provinceSort": 32
		}, {
			"id": 6,
			"provinceName": "辽宁省",
			"provinceRemark": "省份",
			"provinceSort": 8
		}, {
			"id": 7,
			"provinceName": "吉林省",
			"provinceRemark": "省份",
			"provinceSort": 9
		}, {
			"id": 8,
			"provinceName": "黑龙江省",
			"provinceRemark": "省份",
			"provinceSort": 10
		}, {
			"id": 9,
			"provinceName": "上海市",
			"provinceRemark": "直辖市",
			"provinceSort": 3
		}, {
			"id": 10,
			"provinceName": "江苏省",
			"provinceRemark": "省份",
			"provinceSort": 11
		}, {
			"id": 11,
			"provinceName": "浙江省",
			"provinceRemark": "省份",
			"provinceSort": 12
		}, {
			"id": 12,
			"provinceName": "安徽省",
			"provinceRemark": "省份",
			"provinceSort": 13
		}, {
			"id": 13,
			"provinceName": "福建省",
			"provinceRemark": "省份",
			"provinceSort": 14
		}, {
			"id": 14,
			"provinceName": "江西省",
			"provinceRemark": "省份",
			"provinceSort": 15
		}, {
			"id": 15,
			"provinceName": "山东省",
			"provinceRemark": "省份",
			"provinceSort": 16
		}, {
			"id": 16,
			"provinceName": "河南省",
			"provinceRemark": "省份",
			"provinceSort": 17
		}, {
			"id": 17,
			"provinceName": "湖北省",
			"provinceRemark": "省份",
			"provinceSort": 18
		}, {
			"id": 18,
			"provinceName": "湖南省",
			"provinceRemark": "省份",
			"provinceSort": 19
		}, {
			"id": 19,
			"provinceName": "广东省",
			"provinceRemark": "省份",
			"provinceSort": 20
		}, {
			"id": 20,
			"provinceName": "海南省",
			"provinceRemark": "省份",
			"provinceSort": 24
		}, {
			"id": 21,
			"provinceName": "广西壮族自治区",
			"provinceRemark": "自治区",
			"provinceSort": 28
		}, {
			"id": 22,
			"provinceName": "甘肃省",
			"provinceRemark": "省份",
			"provinceSort": 21
		}, {
			"id": 23,
			"provinceName": "陕西省",
			"provinceRemark": "省份",
			"provinceSort": 27
		}, {
			"id": 24,
			"provinceName": "新疆维吾尔自治区",
			"provinceRemark": "自治区",
			"provinceSort": 31
		}, {
			"id": 25,
			"provinceName": "青海省",
			"provinceRemark": "省份",
			"provinceSort": 26
		}, {
			"id": 26,
			"provinceName": "宁夏回族自治区",
			"provinceRemark": "自治区",
			"provinceSort": 30
		}, {
			"id": 27,
			"provinceName": "重庆市",
			"provinceRemark": "直辖市",
			"provinceSort": 4
		}, {
			"id": 28,
			"provinceName": "四川省",
			"provinceRemark": "省份",
			"provinceSort": 22
		}, {
			"id": 29,
			"provinceName": "贵州省",
			"provinceRemark": "省份",
			"provinceSort": 23
		}, {
			"id": 30,
			"provinceName": "云南省",
			"provinceRemark": "省份",
			"provinceSort": 25
		}, {
			"id": 31,
			"provinceName": "西藏自治区",
			"provinceRemark": "自治区",
			"provinceSort": 29
		}, {
			"id": 32,
			"provinceName": "台湾省",
			"provinceRemark": "省份",
			"provinceSort": 7
		}, {
			"id": 33,
			"provinceName": "澳门特别行政区",
			"provinceRemark": "特别行政区",
			"provinceSort": 33
		}, {
			"id": 34,
			"provinceName": "香港特别行政区",
			"provinceRemark": "特别行政区",
			"provinceSort": 34
		}]
	}
}

